name: solar system workflow

on: workflow-dispatch:
    push:
        brances:
            - main
            - feature/*

jobs:
    unit-testing:
        name: Unit testing
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v7
            
            - name: setup nodejs
              uses: actions/setup-node@v4
              with: 
                node-version: 18
            - name: Install dependences
              run: npm install
            - name: Unit Testing
              run: npm test